<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.telran.trello.tests.TeamCreationTests" tests="7" skipped="0" failures="2" errors="0" timestamp="2020-02-03T21:27:47" hostname="DESKTOP-U7V5MJ9" time="163.421">
  <properties/>
  <testcase name="teamCreationTestFromHeader" classname="com.telran.trello.tests.TeamCreationTests" time="32.053"/>
  <testcase name="teamCreationTestFromHeaderCSV[0](TeamData{teamName='a', teamDescr='d'})" classname="com.telran.trello.tests.TeamCreationTests" time="16.458"/>
  <testcase name="teamCreationTestFromHeaderCSV[1](TeamData{teamName='clnsjbbw4kmkfqh_kmjvi', teamDescr='12nsjbbw4kmkfqhkmjvi'})" classname="com.telran.trello.tests.TeamCreationTests" time="16.615"/>
  <testcase name="teamCreationTestFromHeaderCSV[2](TeamData{teamName='&quot;gRKevt0sLwuxJn6sHBitYHUO2ikmH D8F9weec', teamDescr='18AqLcEeEWulk6niGVdelIGX5K8Q4s7w2Vuv1G1I5fHJcprShO5kdqTeK29rq&quot;'})" classname="com.telran.trello.tests.TeamCreationTests" time="16.825"/>
  <testcase name="teamCreationTestFromHeaderWhithNameOnly" classname="com.telran.trello.tests.TeamCreationTests" time="16.229"/>
  <testcase name="teamCreationTestFromHeaderWithDP[0](name DP, description DP)" classname="com.telran.trello.tests.TeamCreationTests" time="26.401">
    <failure message="java.lang.AssertionError: expected [6] but found [0]" type="java.lang.AssertionError">java.lang.AssertionError: expected [6] but found [0]
	at org.testng.Assert.fail(Assert.java:97)
	at org.testng.Assert.assertEqualsImpl(Assert.java:136)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:839)
	at org.testng.Assert.assertEquals(Assert.java:849)
	at com.telran.trello.tests.TeamCreationTests.teamCreationTestFromHeaderWithDP(TeamCreationTests.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:770)
	at org.testng.TestRunner.run(TestRunner.java:591)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:141)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
</failure>
  </testcase>
  <testcase name="teamCreationTestFromHeaderWithDP[1](DPn, )" classname="com.telran.trello.tests.TeamCreationTests" time="38.373">
    <failure message="java.lang.AssertionError: expected [1] but found [7]" type="java.lang.AssertionError">java.lang.AssertionError: expected [1] but found [7]
	at org.testng.Assert.fail(Assert.java:97)
	at org.testng.Assert.assertEqualsImpl(Assert.java:136)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:839)
	at org.testng.Assert.assertEquals(Assert.java:849)
	at com.telran.trello.tests.TeamCreationTests.teamCreationTestFromHeaderWithDP(TeamCreationTests.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:770)
	at org.testng.TestRunner.run(TestRunner.java:591)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:141)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
</failure>
  </testcase>
  <system-out><![CDATA[23:27:47.359 [Test worker] INFO  com.telran.trello.tests.TestBase - Start test teamCreationTestFromHeader with parameters[]
23:28:19.423 [Test worker] INFO  com.telran.trello.utils.Listener - teamCreationTestFromHeader PASSED
23:28:19.423 [Test worker] INFO  com.telran.trello.tests.TestBase - Stop test public void com.telran.trello.tests.TeamCreationTests.teamCreationTestFromHeader() throws java.lang.InterruptedException
23:28:19.428 [Test worker] INFO  com.telran.trello.tests.TestBase - Start test teamCreationTestFromHeaderCSV with parameters[TeamData{teamName='a', teamDescr='d'}]
23:28:35.898 [Test worker] INFO  com.telran.trello.utils.Listener - teamCreationTestFromHeaderCSV PASSED
23:28:35.899 [Test worker] INFO  com.telran.trello.tests.TestBase - Stop test public void com.telran.trello.tests.TeamCreationTests.teamCreationTestFromHeaderCSV(com.telran.trello.model.TeamData) throws java.lang.InterruptedException
23:28:35.900 [Test worker] INFO  com.telran.trello.tests.TestBase - Start test teamCreationTestFromHeaderCSV with parameters[TeamData{teamName='clnsjbbw4kmkfqh_kmjvi', teamDescr='12nsjbbw4kmkfqhkmjvi'}]
23:28:52.531 [Test worker] INFO  com.telran.trello.utils.Listener - teamCreationTestFromHeaderCSV PASSED
23:28:52.532 [Test worker] INFO  com.telran.trello.tests.TestBase - Stop test public void com.telran.trello.tests.TeamCreationTests.teamCreationTestFromHeaderCSV(com.telran.trello.model.TeamData) throws java.lang.InterruptedException
23:28:52.535 [Test worker] INFO  com.telran.trello.tests.TestBase - Start test teamCreationTestFromHeaderCSV with parameters[TeamData{teamName='"gRKevt0sLwuxJn6sHBitYHUO2ikmH D8F9weec', teamDescr='18AqLcEeEWulk6niGVdelIGX5K8Q4s7w2Vuv1G1I5fHJcprShO5kdqTeK29rq"'}]
23:29:09.385 [Test worker] INFO  com.telran.trello.utils.Listener - teamCreationTestFromHeaderCSV PASSED
23:29:09.387 [Test worker] INFO  com.telran.trello.tests.TestBase - Stop test public void com.telran.trello.tests.TeamCreationTests.teamCreationTestFromHeaderCSV(com.telran.trello.model.TeamData) throws java.lang.InterruptedException
23:29:09.389 [Test worker] INFO  com.telran.trello.tests.TestBase - Start test teamCreationTestFromHeaderWhithNameOnly with parameters[]
23:29:25.633 [Test worker] INFO  com.telran.trello.utils.Listener - teamCreationTestFromHeaderWhithNameOnly PASSED
23:29:25.634 [Test worker] INFO  com.telran.trello.tests.TestBase - Stop test public void com.telran.trello.tests.TeamCreationTests.teamCreationTestFromHeaderWhithNameOnly() throws java.lang.InterruptedException
23:29:25.637 [Test worker] INFO  com.telran.trello.tests.TestBase - Start test teamCreationTestFromHeaderWithDP with parameters[name DP, description DP]
23:29:52.062 [Test worker] ERROR com.telran.trello.utils.Listener - teamCreationTestFromHeaderWithDP
 FAILED
java.lang.AssertionError: expected [6] but found [0]
23:29:52.394 [Test worker] INFO  c.t.trello.fw.ApplicationManager - 
Created screenshot: C:\Users\romic\Documents\GitHub\Trello_qa22-roman\src\test\screenshots\screen-1580765392393.png
23:29:52.395 [Test worker] INFO  com.telran.trello.tests.TestBase - Stop test public void com.telran.trello.tests.TeamCreationTests.teamCreationTestFromHeaderWithDP(java.lang.String,java.lang.String) throws java.lang.InterruptedException
23:29:52.397 [Test worker] INFO  com.telran.trello.tests.TestBase - Start test teamCreationTestFromHeaderWithDP with parameters[DPn, ]
23:30:30.792 [Test worker] ERROR com.telran.trello.utils.Listener - teamCreationTestFromHeaderWithDP
 FAILED
java.lang.AssertionError: expected [1] but found [7]
23:30:31.326 [Test worker] INFO  c.t.trello.fw.ApplicationManager - 
Created screenshot: C:\Users\romic\Documents\GitHub\Trello_qa22-roman\src\test\screenshots\screen-1580765431324.png
23:30:31.327 [Test worker] INFO  com.telran.trello.tests.TestBase - Stop test public void com.telran.trello.tests.TeamCreationTests.teamCreationTestFromHeaderWithDP(java.lang.String,java.lang.String) throws java.lang.InterruptedException
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
